[package]
name = "xml_to_lua"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs = "0.8.4"
serde = "1.0.158"
clap = "3.2.23"
lazy_static = "1.4.0"